[versions]
jacoco = "0.8.12"
checkstyle = "10.17.0"
# jhipster-needle-gradle-dependency-catalog-version - JHipster will add additional versions for convention plugins heref

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version = "8.5.0" }
springdoc-openapi-starter-webflux-api = { module = "org.springdoc:springdoc-openapi-starter-webflux-api", version = "2.5.0" }
cucumber-bom = { module = "io.cucumber:cucumber-bom", version = "7.18.0" }
testng = { module = "org.testng:testng", version = "7.10.2" }
commons-beanutils = { module = "commons-beanutils:commons-beanutils", version = "1.9.4" }
# jhipster-needle-gradle-dependency-catalog-libraries - JHipster will add additional libraries versions

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.0" }
# jhipster-needle-gradle-dependency-catalog-plugins - JHipster will add additional plugins versions
